### ISSUE TITLE
是否考虑出一个简短的文档简单的描述image-builder的移植过程

### ISSUE THREAD

**Issue by mailonghua** [Embedfire/ebf-image-builder#1]
野火开发板是我最新欢的开发板之一  
但是在日常的使用中也会考虑自己diy一些ARM SoC,那么想要再直接使用image-builder编译对应的soc的  
debian 根文件系统就变的非常不便，若是有可能描述您在移植过程中的记录，或者如何修改该ex能够复用新的
soc，那真是太棒了

**Comment by flyleaf91** [comment]
有计划，正在移植并添加其它芯片，现在image-builder已经简化、更新至2.0版本，后续会基于该分支开发：https://github.com/Embedfire/ebf-image-builder/tree/image-builder_2.0

**Comment by mailonghua** [comment]
若是能够在以BB的为版本基础，将适配的一个SOC的板子的修改能够在git中看到，那么那真是非常棒的体验，因为这样就能够清晰的知道若是新移植到新的soc上应该做那些工作

**Comment by mailonghua** [comment]
将该项目大概看了一遍，简单的整理了一下，若是有时间可以看一下是否有缺失或者补充的
https://github.com/mailonghua/ebf-image-builder/blob/master/%E7%A7%BB%E6%A4%8D%E6%96%B0%E7%9A%84SOC%E9%9C%80%E8%A6%81%E9%85%8D%E7%BD%AE%E7%9A%84%E6%96%87%E4%BB%B6.md

**Comment by flyleaf91** [comment]
很赞，后面我们也参考一下整理出来，基于2.0分支，简化了很多内容

**Comment by mailonghua** [comment]
会订阅你的状态，期待你们的更新，会持续关注野火～祝越来越好
